import mongoose from "mongoose";

const documentRequestSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    organizationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      required: true,
      index: true
    },
    type: {
      type: String,
      enum: ["recommendation", "certificate", "experience"],
      required: true,
    },
    customType: {
      type: String,
    },
    reason: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ["pending", "approved", "rejected", "generated", "downloaded"],
      default: "pending",
      index: true,
    },
    generatedDocumentUrl: {
      type: String, // Cloudinary URL of the PDF generated by Admin
    },
    adminComments: {
      type: String,
    },
    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    reviewedAt: {
      type: Date,
    },
    completedAt: {
      type: Date, // When document is generated
    },
  },
  { timestamps: true }
);

export default mongoose.model("DocumentRequest", documentRequestSchema);
